### ISSUE TITLE
Todo list: V3 functionality and documentation

### ISSUE THREAD

**Issue by telegraphic** [telegraphic/hickle#28]
After pretty major refactor, there's some tidying to do, and also some other functionality that could be added. Here's the new todo list:
- [x] Python 3 support (https://github.com/telegraphic/hickle/issues/8)
- [x] Refactor code for DRY niceness
- [x] Sphinx documentation / readthedocs
- [x] Write formal hickle specification V2, with metadata moved into HDF5 attributes
- [ ] Look at parsing `globals()` and `locals()` to save entire state (may be a bad idea!)
- [ ] Create 'plugin' system to allow users to add their own datatype handling, without adding loads of dependencies on hickle itself.
  - [ ] Consider handling Pandas DataFrame type (may be a bad idea, adds pandas dependency)
  - [x] Consider handling Astropy types
- [x] Add versioning and extra metadata so hickle files can be matched to the Python and Hickle version that created them.
- [x] Add warnings if trying to open Py 2 file in Py 3 and vice-versa, and then do best-effort to open it anyway.
- [x] Dump objects into h5py.group (See #54)
- [x] Ensure user-defined object handles OK (See #39)
- [x] Add [Collections](https://docs.python.org/3/library/collections.html) support

**Comment by telegraphic** [comment]
Update - `dev` branch has moved toward a plugin system, but is still a little clunky. Also has Py3 support.

**Comment by telegraphic** [comment]
New todo: Better handling for when you use `path=` to dump multiple hickles into one file and then forget that you did. Currently you'll see an error unless you get the path correct; may require extra metadata in the root group.

**Comment by peendebak** [comment]
@telegraphic Is there an example of how to use the plugin system? I would like to do something as:
```
hickle.register_class(myclass, serialize_function, unserialize_function)
```

**Comment by telegraphic** [comment]
@peendebak currently the plugin system is non-existent, but I really like this as an approach and think it could work

**Comment by telegraphic** [comment]
@peendebak there is now a `register_class` function, currently in `hickle.lookup.register_class`. I've ported the [astropy dump/load functions](https://github.com/telegraphic/hickle/blob/master/hickle/loaders/load_astropy.py) to use this as a test.

I found I needed a few other extra arguments to get it working. Firstly, to check if the array is to be iterated over (e.g. a list, `[1, 2, 'apple', np.array([1,2,3])`) or a dataset-like array (e.g. np.array). Secondly, a flag to say whether something requires sorting.

```python
def register_class(myclass_type, hkl_str, dump_function, load_function,
                   to_sort=True, ndarray_check_fn=None):
    """ Register a new hickle class.

    Args:
        myclass_type type(class): type of class
        dump_function (function def): function to write data to HDF5
        load_function (function def): function to load data from HDF5
        is_iterable (bool): Is the item iterable?
        hkl_str (str): String to write to HDF5 file to describe class
        to_sort (bool): If the item is iterable, does it require sorting?
        ndarray_check_fn (function def): function to use to check if array should be iterated

    """
```

Still very much in beta. I anticipate it being used like so:

```python
import hickle as hkl

class SuperList(list):
    def __init__(self, *args, **kwargs):
        super(SuperList, self).__init__(*args, **kwargs)
        self.new_attribute = 'hello'

def dump_superlist(py_obj, h_group, call_id=0, **kwargs):
    """ dumps an SuperList object to h5py file

    Args:
        py_obj: python object to dump; should be a numpy array or np.ma.array (masked)
        h_group (h5.File.group): group to dump data into.
        call_id (int): index to identify object's relative location in the iterable.
    """
    d = h_group.create_dataset('data_%i' % call_id, data=py_obj, **kwargs)
    d.attrs["type"] = [b'super_list']

def load_superlist(h_node):
    py_type, data = hkl.helpers.get_type_and_data(h_node)
    return SuperList(data)

def check_is_superlist(py_obj):
    return isinstance(py_obj, SuperList)

hkl.lookup.register_class(SuperList, 'super_list', dump_superlist, load_superlist, to_sort=True, ndarray_check_fn=check_is_superlist)

a = SuperList([1,2,3])
hkl.dump(a, 'test.hkl')
b = hkl.load('test.hkl')
```

**Comment by telegraphic** [comment]
Closing as part of a tidy-up -- we are on V4 already and most has been implemented.
